# Generated by Django 4.1.1 on 2022-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuttingtypes',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=150, null=True)),
                ('c_colorcode', models.CharField(blank=True, max_length=200, null=True)),
                ('c_multiwithdiamonds', models.BooleanField(blank=True, null=True)),
                ('c_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('isdelete', models.BooleanField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
                ('objid', models.CharField(blank=True, max_length=250, null=True)),
                ('old_userid', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'cuttingtypes',
                'managed': False,
            },
        ),
    ]
